### PR TITLE
Change StatusBar icon to new app icon style.

### PR DESCRIPTION
**Pull request by Skyearn**
[BLEUnlock.ai.zip](https://github.com/ts1/BLEUnlock/files/6606108/BLEUnlock.ai.zip)

### CODE REVIEW

**Comment by ts1** [comment]
Thank you for the pull request.
However, what exactly is the purpose of this?
It doesn't seem to have changed, at least from what I can see.

**Comment by Skyearn** [comment]
> Thank you for the pull request.
> However, what exactly is the purpose of this?
> It doesn't seem to have changed, at least from what I can see.

It is mainly the adjustment of size and proportion.

**Comment by Skyearn** [comment]
> Thank you for the pull request.
> However, what exactly is the purpose of this?
> It doesn't seem to have changed, at least from what I can see.

794B20BC-5BD6-4672-8662-6FF6EB7EE0C9
[BLEUnlock.ai.zip](https://github.com/ts1/BLEUnlock/files/6623845/BLEUnlock.ai.zip)

**Comment by Skyearn** [comment]
Consistent with the application icon. The proportion is reduced equally.

**Comment by ts1** [comment]
Thank you for the explanation. And for the work, of course.
I think I might be blind.

**Pull request merged**
