### PR TITLE
Localizations update

### PR DESCRIPTION
**Pull request by cyberclaus**
Unfortunately my last changes were not included in the fork. Here are the lastest translations in da, de, nb, and sv.

### CODE REVIEW

**Comment by ts1** [comment]
I merged [this branch](https://github.com/ts1/BLEUnlock/pull/73)  and now your branch is conflicting.
Can you provide a PR based on my new master branch?
Also I would like a **clean** commit.
If that is difficult for you, I'll squash your changes into one commit.

**Comment by cyberclaus** [comment]
Tried to delete my fork, get a new one and provide a clean PR but it didn't  work out as expected. I'm pretty new to Github, sorry. So if you please can squash my changes into one commit. Thanks a lot.

**Comment by ts1** [comment]
Okay, I'll do the rest.
You have already made an indescribable contribution.

**Comment by ts1** [comment]
Your changes are squashed and merged in [this commit](https://github.com/ts1/BLEUnlock/commit/c40572cf41bf8ed0c959f25a8e87ddddfee69455).
Thank you!

**Pull request closed without merging**
